name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! Thank you for support and feel free to contribute ⚡'' First Issue'
        pr-message: 'Hi! Thank you for contribute and enjoy the journey 🚀'' First Pull Request'
